### ISSUE TITLE
No loader is configured for ".svelte" files

### ISSUE THREAD

**Issue by dsignr** [inertiajs/inertia-phoenix#17]
Hi! I tried running this with Svelte, however, I was greeted with these errors. And after a little bit digging, it turns out the default ESBUILD configuration in Phoenix doesn't support plugins (which is needed for SVELTE support). Is my assumption correct that a custom build step is needed, such as Webpack?

```
[watch] build finished, watching for changes...
✘ [ERROR] No loader is configured for ".svelte" files: node_modules/@inertiajs/svelte/src/Link.svelte

    node_modules/@inertiajs/svelte/src/index.js:2:32:
      2 │ export { default as Link } from './Link.svelte'
        ╵                                 ~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".svelte" files: node_modules/@inertiajs/svelte/src/App.svelte

    node_modules/@inertiajs/svelte/src/createInertiaApp.js:2:16:
      2 │ import App from './App.svelte'
        ╵                 ~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".svelte" files: node_modules/@inertiajs/svelte/src/SSR.svelte

    node_modules/@inertiajs/svelte/src/createInertiaApp.js:3:16:
      3 │ import SSR from './SSR.svelte'
        ╵                 ~~~~~~~~~~~~~~
```

My `app.js` looks like this:

```js
import { createInertiaApp } from '@inertiajs/svelte'

createInertiaApp({
    resolve: name => {
      const pages = import(`./pages/${name}.svelte`)
      return pages[`./pages/${name}.svelte`]
    },
    setup({ el, App, props }) {
      new App({ target: el, props })
    },
})```

**Comment by tonydangblog** [comment]
Hi @dsignr - That's correct. An esbuild plugin is needed to process Svelte files. There is a guide in the official Phoenix [docs](https://hexdocs.pm/phoenix/asset_management.html#esbuild-plugins) for adding esbuild plugins.

Additionally, I have a repo with a complete guide for setting up the Phoenix Inertia adapter with Svelte [here](https://github.com/tonydangblog/phoenix-inertia-svelte) as well :)
