### ISSUE TITLE
assign_errors does not support nested associations?

### ISSUE THREAD

**Issue by dsignr** [inertiajs/inertia-phoenix#19]
Hi, it's  me again. It seems like `assign_errors` does not work for nested associations, unless I am doing something wrong:

```elixir
#Ecto.Changeset<
  action: :insert,
  changes: %{
    media: [],
    specifications: [
      #Ecto.Changeset<
        action: :insert,
        changes: %{delete: false},
        errors: [
          name: {"can't be blank", [validation: :required]},
          value: {"can't be blank", [validation: :required]}
        ],
        data: #Acme.Storefront.Product.Specification<>,
        valid?: false
      >,
      #Ecto.Changeset<
        action: :insert,
        changes: %{delete: false},
        errors: [
          name: {"can't be blank", [validation: :required]},
          value: {"can't be blank", [validation: :required]}
        ],
        data: #Acme.Storefront.Product.Specification<>,
        valid?: false
      >,
      #Ecto.Changeset<
        action: :insert,
        changes: %{delete: false},
        errors: [
          name: {"can't be blank", [validation: :required]},
          value: {"can't be blank", [validation: :required]}
        ],
        data: #Acme.Storefront.Product.Specification<>,
        valid?: false
      >
    ]
  },
  errors: [
    shipping_options: {"is invalid", [type: {:array, :map}]},
    name: {"can't be blank", [validation: :required]},
    description: {"can't be blank", [validation: :required]},
    slug: {"can't be blank", [validation: :required]},
    price: {"can't be blank", [validation: :required]}
  ],
  data: #Acme.Storefront.Product<>,
  valid?: false
>
```

<img width="644" alt="image" src="https://github.com/user-attachments/assets/09660d66-d8e8-473f-8192-6cb2893b5c06">

This is what the XHR response looks like. I guess I can write an `Enum.reduce` for each of the nested entity with errors and assign it to the `conn`, but just wanted to check if this is the only way as of now?

Thanks in advance!

**Comment by derrickreimer** [comment]
Hey @dsignr, the error serializer should be picking up nested errors. We have a test case that is using an embedded schema: https://github.com/inertiajs/inertia-phoenix/blob/0ea7b0b59a83729f1fa2310b04dce50520777e22/test/inertia_test.exs#L321-L337. 

Under the covers, we're using `Ecto.Changeset.traverse_errors/2` to build the error map and then running some simple logic to flatten the errors down into a flat map (so that the shape aligns with the TypeScript types defined on the client-side for errors): https://github.com/inertiajs/inertia-phoenix/blob/0ea7b0b59a83729f1fa2310b04dce50520777e22/lib/inertia/errors.ex#L20

We have some unit tests for the flattening logic here: https://github.com/inertiajs/inertia-phoenix/blob/main/test/inertia/errors_test.exs

I wonder, if you run `Ecto.Changeset.traverse_errors` on that changeset you shared, do those nested errors appear in the resulting map?

**Comment by derrickreimer** [comment]
Also worth noting that I'd like to refactor things a bit to allow developers to choose their error serialization strategy (or implement their own), especially since I don't believe Inertia has strong opinions/requirements around the shape of errors. It might make sense to try to relax the TypeScript types for them to allow nested maps, arrays, etc. if go this route.

**Comment by dsignr** [comment]
> Hey @dsignr, the error serializer should be picking up nested errors. We have a test case that is using an embedded schema:
> 
> https://github.com/inertiajs/inertia-phoenix/blob/0ea7b0b59a83729f1fa2310b04dce50520777e22/test/inertia_test.exs#L321-L337
> 
> .
> Under the covers, we're using `Ecto.Changeset.traverse_errors/2` to build the error map and then running some simple logic to flatten the errors down into a flat map (so that the shape aligns with the TypeScript types defined on the client-side for errors):
> 
> https://github.com/inertiajs/inertia-phoenix/blob/0ea7b0b59a83729f1fa2310b04dce50520777e22/lib/inertia/errors.ex#L20
> 
> We have some unit tests for the flattening logic here: https://github.com/inertiajs/inertia-phoenix/blob/main/test/inertia/errors_test.exs
> 
> I wonder, if you run `Ecto.Changeset.traverse_errors` on that changeset you shared, do those nested errors appear in the resulting map?

Let me run it through the serializer and update here.

**Comment by dsignr** [comment]
Oddly enough, when I used a custom function, it outputs exactly the error object I would expect it to. I picked this function up from maybe an earlier version of what was generated for `mix phx.gen.auth` when It supported some variation of JSON APIs out of the box and I can see it is very similar to the one you have used in your function call as well.

Here is what the function that I used worked:

```elixir
 defp translate_error({msg, opts}) do
    # You can make use of gettext to translate error messages by
    # uncommenting and adjusting the following code:

    # if count = opts[:count] do
    #   Gettext.dngettext(MyAppWeb.Gettext, "errors", msg, msg, count, opts)
    # else
    #   Gettext.dgettext(MyAppWeb.Gettext, "errors", msg, opts)
    # end

    Enum.reduce(opts, msg, fn {key, value}, acc ->
      String.replace(acc, "%{#{key}}", fn _ -> to_string(value) end)
    end)
  end
```

Long story short, here is the function call:
```elixir
Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
```

And here is the response, perfectly working:
```elixir
%{
  name: ["can't be blank"],
  description: ["can't be blank"],
  price: ["can't be blank"],
  shipping_options: ["is invalid"],
  slug: ["can't be blank"],
  specifications: [
    %{name: ["can't be blank"], value: ["can't be blank"]},
    %{name: ["can't be blank"], value: ["can't be blank"]}
  ]
}
```

Somehow by the time it passes through `assign_errors` the specifications object is being stripped out. And I tried it like 2-3 times with different variations.

Corresponding params object:

```elixir
%{
  "description" => nil,
  "features" => nil,
  "name" => nil,
  "price" => nil,
  "specifications" => [
    %{"delete" => false, "id" => nil, "name" => "", "unit" => "", "value" => ""},
    %{"delete" => false, "id" => nil, "name" => "", "unit" => "", "value" => ""}
  ]
}
```

I tried passing in my custom function, but still doesn't seem to work:

```elixir
conn
|> assign_errors(changeset, &translate_error/1)
|> redirect(to: ~p"/admin/storefront/products/new")
```

I tried this and it immediately threw an error:

```
conn
|> assign_errors(Ecto.Changeset.traverse_errors(changeset, &translate_error/1))
|> redirect(to: ~p"/admin/storefront/products/new")
```

```
Request: POST /admin/storefront/products
** (exit) an exception was raised:
    ** (ArgumentError) expected string value for name, got ["can't be blank"]
        (inertia 0.10.0) lib/inertia/errors.ex:41: anonymous fn/1 in Inertia.Errors.validate_error_map!/1
        (elixir 1.15.7) lib/enum.ex:989: anonymous fn/3 in Enum.each/2
        (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
        (elixir 1.15.7) lib/enum.ex:2522: Enum.each/2
        (inertia 0.10.0) lib/inertia/errors.ex:35: Inertia.Errors.validate_error_map!/1
        (inertia 0.10.0) lib/inertia/controller.ex:117: Inertia.Controller.assign_errors/2
```

%{
  name: "can't be blank",
  description: "can't be blank",
  price: "can't be blank",
  shipping_options: "is invalid",
  slug: "can't be blank",
  specifications: [
    %{name: "can't be blank", value: "can't be blank"},
    %{name: "can't be blank", value: "can't be blank"}
  ]
}

So, I tried directly passing in this nested map:

```
%{
          "name" => "can't be blank",
          "description" => "can't be blank",
          "price" => "can't be blank",
          "shipping_options" => "is invalid",
          "slug" => "can't be blank",
          "specifications" => [
               %{"name" => "can't be blank", "value" => "can't be blank"},
               %{"name" => "can't be blank", "value" => "can't be blank"}
          ]
}
```
And immediately, I got this:

```
expected string value for specifications, got [%{"name" => "can't be blank", "value" => "can't be blank"}, %{"name" => "can't be blank", "value" => "can't be blank"}]
```
(actually, this is expected since the readme says to use indexed notation)

So, I passed it an indexed notation directly:

```
%{
          "name" => "can't be blank",
          "description" => "can't be blank",
          "price" => "can't be blank",
          "shipping_options" => "is invalid",
          "slug" => "can't be blank",
          "specifications[0].name" => "can't be blank",
          "specifications[0].value" => "can't be blank",
          "specifications[1].name" => "can't be blank",
          "specifications[1].value" => "can't be blank",
 }
```
But then, it was still not making it to the frontend:
<img width="652" alt="image" src="https://github.com/user-attachments/assets/422d2960-6093-4776-be2a-e402fd26e194">

So, to me that confirms the nested objects are not being passed to the frontend.

Hope. this helps.

**Comment by dsignr** [comment]
Before I call it a day, here is how I managed to fix this:

```elixir
 def new(conn, _params) do
    changeset = Storefront.change_product(%Product{})

    conn
    |> assign_prop(:text, "Hello world")
    |> assign_errors(changeset, &translate_error/1)
    |> render_inertia("admin/storefront/products/new")
end

def create(conn, %{"product" => product_params}) do
    IO.inspect product_params
    case Storefront.create_product(product_params) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: ~p"/admin/storefront/products")

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> assign_errors(changeset, &translate_error/1)
        # |> redirect(to: ~p"/admin/storefront/products/new") <-- this was the issue
        |> render_inertia("admin/storefront/products/new")
    end
end
```

Changing `redirect(to: ~p"/admin/storefront/products/new")` to `render_inertia("admin/storefront/products/new")` fixed it.

As per Inertia's documentation (not phoenix-inertia's), the redirect should have carry forwarded the error messages as is. 

But, in Phoenix, when you do the redirect, it goes from (in my case) `def create at POST /products` to a 302 redirect to `def new at GET /products/new`, this means it goes through a different changeset again, which stripped off the nested assocs as if it were a new object.

This is the only logical explanation that I can think of.

**Comment by derrickreimer** [comment]
Ah! It looks like the `assign_errors` on your new handler is indeed clobbering the errors that get carried over from the redirect. I'd recommend removing that line, since there shouldn't be validation errors in need of rendering from a freshly-built changeset struct.

```diff
   def new(conn, _params) do
      changeset = Storefront.change_product(%Product{})
  
      conn
      |> assign_prop(:text, "Hello world")
-     |> assign_errors(changeset, &translate_error/1)
      |> render_inertia("admin/storefront/products/new")
  end
```

With that line removed, errors should get propagated over the redirect hop as documented.

**Comment by dsignr** [comment]
> Ah! It looks like the `assign_errors` on your new handler is indeed clobbering the errors that get carried over from the redirect. I'd recommend removing that line, since there shouldn't be validation errors in need of rendering from a freshly-built changeset struct.
> 
> ```diff
>    def new(conn, _params) do
>       changeset = Storefront.change_product(%Product{})
>   
>       conn
>       |> assign_prop(:text, "Hello world")
> -     |> assign_errors(changeset, &translate_error/1)
>       |> render_inertia("admin/storefront/products/new")
>   end
> ```
> 
> With that line removed, errors should get propagated over the redirect hop as documented.
> 
> Are you seeing the nested errors coming through now?

Yup, that did the trick. I see it coming through now. Thanks @derrickreimer !
Closing this as it is a user error and not the library. Thank you again for your time :)
