### ISSUE TITLE
What is the recommended way to test an inertia-phoenix endpoint?

### ISSUE THREAD

**Issue by rverton** [inertiajs/inertia-phoenix#21]
Hi,
what is the recommended way to test an inertia endpoint?

As inertia-phoenix is able to return data as JSON I would prefer to assert against this output so I do not have to parse HTML. To do this, the `X-Inertia` header can be set, so the response will be JSON. For GET requests however, the `X-Inertia-Version` header has to be set to the correct version. This version is calculated here: https://github.com/inertiajs/inertia-phoenix/blob/0b9eaae74ef20ca0b2ae7a2e13cd0fc9f5355c9f/lib/inertia/plug.ex#L138-L144

As this method is private, I don't have access to the current version. Any recommendation how to solve this in an idiomatic way other than copying the static path hash calculation? The following snippet works as soon as I hardcode the current version number in the header.
```elixir
  setup %{conn: conn} do
    conn =
      put_req_header(conn, "x-inertia-version", "xyz")
      |> put_req_header("x-inertia", "true")

    {:ok, conn: conn}
  end

  describe "index" do
    test "lists all objects", %{conn: conn} do
      conn = get(conn, ~p"/objects")
      assert %{"component" => "Objects/Index"} = json_response(conn, 200)
      # ...
    end
  end
```

**Comment by derrickreimer** [comment]
Hey @rverton! Great question. I've been meaning to add some official test helpers to this library. Here's what I've been playing with in my own projects:

```elixir
  describe "index" do
    test "lists all objects", %{conn: conn} do
      conn = get(conn, ~p"/objects")
      assert inertia_component(conn) == "Objects/Index"
      assert %{foo: "bar"} = inertia_props(conn)
      # ...
    end
  end

  defp inertia_props(conn) do
    conn.private.inertia_page.props
  end

  defp inertia_component(conn) do
    conn.private.inertia_page.component
  end
```

It would be good to get these implemented as official helpers, since they rely on private connection data, but in the meantime this should work pretty well. You shouldn't need to mess with setting Inertia headers using this approach.

**Comment by rverton** [comment]
Thanks a lot, this makes it really simple!
