### ISSUE TITLE
Inertiajs not compatible with the newest 1.0.0 Liveview while still requring Liveview 0.18

### ISSUE THREAD

**Issue by Bedtimestory9** [inertiajs/inertia-phoenix#25]
Now I'm having this error and it seems to be related to the newly introduced Liveview 1.0.0
```

   warning: Phoenix.Component.used_input?/1 is undefined or private
     │
 295 │     errors = if Phoenix.Component.used_input?(form_field), do: form_field.errors, else: []
     │                                   ~
     │
     └─ lib/compocenter_web/components/core_components.ex:295:35: CompocenterWeb.CoreComponents."input (overridable 1)"/1
```
I'm using --no-live why do I still need to deal with liveview, and if so, how do I fix this?

**Comment by derrickreimer** [comment]
Hey @Bedtimestory9, it looks like this warning is coming from your application's `CoreComponents` module.

**Comment by Bedtimestory9** [comment]
Hi @derrickreimer, how u doing

Im struggling to scaffold a phoenix + inertia

I started with:
```
mix phx.new compocenter --no-live --no-esbuild --no
-tailwind
```

Then I chose no to install deps
`Fetch and install dependencies? [Yn] n`

I added what's required for inertiajs on mix.exs and config.exs
Then I ran
`mix deps.get`
Result:
`Resolution completed in 0.035s
Because your app depends on inertia ~> 1.0.0-beta.3 which depends on phoenix_live_view ~> 0.18, phoenix_live_view ~> 0.18 is required.
So, because your app depends on phoenix_live_view ~> 1.0.0, version solving failed.`

No problem, I altered Liveview to 0.18 in mix.exs
And ran `mix deps.get` again, this time it installed deps without any problem

Okay now the problem came
`mix assets.setup`

`warning: defining a Gettext backend by calling

    use Gettext, otp_app: ...

is deprecated. To define a backend, call:

    use Gettext.Backend, otp_app: :my_app

Then, instead of importing your backend, call this in your module:

    use Gettext, backend: MyApp.Gettext

  lib/compocenter_web/gettext.ex:23: CompocenterWeb.Gettext (module)

     warning: Phoenix.Component.used_input?/1 is undefined or private
     │
 295 │     errors = if Phoenix.Component.used_input?(field), do: field.errors, else: []
     │                                   ~
     │
     └─ lib/compocenter_web/components/core_components.ex:295:35: CompocenterWeb.CoreComponents."input (overridable 1)"/1`

I restarted all over again and always ran into this, idk

**Comment by Bedtimestory9** [comment]
I built with --no-gettext and still have the same warning, I'm done for now

```
    warning: Phoenix.Component.used_input?/1 is undefined or private
     │
 294 │     errors = if Phoenix.Component.used_input?(field), do: field.errors, else: []
     │                                   ~
     │
     └─ lib/compocenter_web/components/core_components.ex:294:35: CompocenterWeb.CoreComponents."input (overridable 1)"/1
```

**Comment by derrickreimer** [comment]
The `CoreComponents` module is an auto-generated file that Phoenix creates when scaffolding your project, regardless of the `--no-live` flag being passed to the generator. It looks like the `Phoenix.Component.used_input?` function (that gets called in that module's generated code) was introduced after LiveView 0.18.

So to get your project building in the immediate term, you can just clear out the contents of the `CoreComponents` module in your app (or delete the file entirely and remove the `import` inside the `html_helpers` function in your `CompocenterWeb` module).

That said, we should relax the dependencies of this project to accommodate the newly-released LiveView 1.x: https://github.com/inertiajs/inertia-phoenix/issues/26
