### ISSUE TITLE
Using Ecto.Schema as the integration point prevents inertia-phoenix from working easily with other libraries rather than ecto.

### ISSUE THREAD

**Issue by zhangzhen** [inertiajs/inertia-phoenix#27]
Recently I want to use inertia-phoenix with ash. The creator of ash said that it's likely impossible to integrate ash with inertia-phoenix without making improvements to inertia-phoenix: defining a behavior or protocol and making an Ecto.Schema implementation for it. Could you have time to make such improvements?

**Comment by derrickreimer** [comment]
Hey @zhangzhen! Thanks for reaching out. I'm not too familiar with Ash Framework myself, but it seems to be like it would be possible to use Inertia in the controller/view layer and use Ash to manage your domain objects. I'm afraid it's probably not something I'd be able to work on in the near-term, but happy to take a look at a concrete proposal for what a more formal Ash integration could look like!
